# Generated by Django 2.0.6 on 2018-10-14 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Fornecedor')),
                ('tipo', models.CharField(max_length=100, verbose_name='Tipo de fornecedor')),
                ('cnpj', models.IntegerField(verbose_name='CNPJ')),
                ('email', models.CharField(max_length=100, unique=True, verbose_name='E-mail')),
                ('telefone', models.IntegerField(verbose_name='Telefone')),
            ],
        ),
        migrations.CreateModel(
            name='local',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Local')),
            ],
        ),
    ]
