# Generated by Django 2.0.6 on 2019-10-03 21:22

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telefone_Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='endereco',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='telefone_fornecedor',
            name='fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.expressions.Case, to='estoque.fornecedor', verbose_name='Telefone Fornecedor'),
        ),
    ]
