# Generated by Django 2.0.6 on 2018-10-14 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_delete_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='slug',
            field=models.SlugField(default='forn', max_length=100, verbose_name='Identificador'),
        ),
    ]
