# Generated by Django 2.0.6 on 2019-10-03 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_auto_20191003_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telefone_fornecedor',
            name='fornecedor',
        ),
        migrations.DeleteModel(
            name='Telefone_Fornecedor',
        ),
    ]
