# Generated by Django 2.0.6 on 2018-10-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_fornecedor_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='cnpj',
            field=models.BigIntegerField(verbose_name='CNPJ'),
        ),
    ]
