# Generated by Django 2.0.6 on 2019-10-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_auto_20191003_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque_produto',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='Identificador'),
        ),
    ]
