# Generated by Django 2.0.6 on 2018-11-04 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0006_auto_20181104_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoque_materia_prima',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='materia_prima', verbose_name='Imagem'),
        ),
    ]
