# Generated by Django 2.0.6 on 2018-11-25 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_auto_20181125_0847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='altura',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='comprimento',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='diamentro',
        ),
    ]
