# Generated by Django 2.0.6 on 2018-11-04 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_auto_20181014_0627'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='cor',
            field=models.CharField(default=123, max_length=100, verbose_name='Cor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.FileField(default=1, upload_to='imagens/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='tamanho',
            field=models.CharField(default=1, max_length=3, verbose_name='Tamanho'),
            preserve_default=False,
        ),
    ]
