# Generated by Django 2.0.6 on 2018-11-04 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_auto_20181104_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.FileField(blank=True, upload_to='imagens/'),
        ),
    ]
