# Generated by Django 2.0.6 on 2018-11-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_auto_20181125_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='catalogo/produto/', verbose_name='Imagem'),
        ),
    ]
