# Generated by Django 2.0.6 on 2018-11-04 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_auto_20181104_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(upload_to='imagens/', verbose_name='Imagem'),
        ),
    ]
