# Generated by Django 2.0.6 on 2018-11-04 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0008_auto_20181104_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/', verbose_name='Imagem'),
        ),
    ]
