# Generated by Django 2.0.6 on 2018-11-04 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0012_auto_20181104_0354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='cor',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='imagem',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='tamanho',
        ),
    ]
