# Generated by Django 2.0.6 on 2019-10-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGU', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cep',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rg',
            field=models.BigIntegerField(null=True),
        ),
    ]
