# Generated by Django 2.0.6 on 2018-08-26 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGU', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='validacao',
            field=models.CharField(blank=True, max_length=150, unique=True),
        ),
    ]
