# Generated by Django 2.0.6 on 2018-08-26 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGU', '0002_auto_20180826_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='validacao',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
