# Generated by Django 2.0.6 on 2018-09-14 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SGU', '0003_auto_20180914_0329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grupos',
            options={'ordering': ['nome'], 'verbose_name': 'Grupo', 'verbose_name_plural': 'Grupos'},
        ),
        migrations.AlterModelOptions(
            name='permissions',
            options={'ordering': ['groups'], 'verbose_name': 'Permissão', 'verbose_name_plural': 'Permissões'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['nome'], 'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AlterField(
            model_name='cliente',
            name='usuario_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
