# Generated by Django 2.0.6 on 2018-08-26 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SGU', '0003_auto_20180826_0043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='validacao',
        ),
    ]
