# Generated by Django 2.0.6 on 2018-08-26 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGU', '0004_remove_usuario_validacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='validacao',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
