# Generated by Django 2.0.6 on 2018-11-26 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20181126_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoitem',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='checkout.Pedido', verbose_name='Pedido'),
        ),
        migrations.AlterField(
            model_name='pedidoitem',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.Produto', verbose_name='catalogo.produto'),
        ),
    ]
