# Generated by Django 2.0.6 on 2018-11-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20181126_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Aguardando Pagamento'), (1, 'Pago'), (2, 'Cancelada'), (3, 'Enviado para os Correios')], default=0, verbose_name='Situação'),
        ),
    ]
