"""
Django settings for NGKS project.

Generated by 'django-admin startproject' using Django 2.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'lg%b2l7jo-y)-#+pcm5^liy1pwud^s^6(_-r=i1xn80-a4usdn'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #libs
    'bootstrap3',
    'widget_tweaks',
    #apps
    'SGU',
    'core',
    'catalogo',
    'checkout',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'checkout.middleware.cart_item_middleware',
]

ROOT_URLCONF = 'NGKS_Shop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                #apps
                 'core.context_processors.categorias',
            ],
        },
    },
]

WSGI_APPLICATION = 'NGKS_Shop.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'NGKS_Shop',
        'USER': 'root',
        'PASSWORD': 'Z3ld4100%',
        'HOST': 'localhost',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'

#e-mail
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
<<<<<<< HEAD
EMAIL_HOST_USER = 'lmsimpacta@gmail.com'
EMAIL_HOST_PASSWORD = '@impacta123'
EMAIL_PORT = 587

# Thumbnails
THUMBNAIL_ALIASES = {
    '': {
        'imagem_produto': {'size': (200, 250), 'crop': True},
    },
}
=======
EMAIL_HOST_USER = 'allan.turatti@gmail.com'
EMAIL_HOST_PASSWORD = 'Alnmrt132@'
EMAIL_PORT = 587
DEFAULT_FROM_EMAIL = 'admin@djangoecommerce.com'

#Auth
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'index'

#MESSAGE
from django.contrib.messages import constants as messages_constants 
MESSAGE_TAGS = {
    messages_constants.DEBUG: 'debug',
    messages_constants.INFO:  'info',
    messages_constants.SUCCESS:'sucess',
    messages_constants.WARNING:'warning',
    messages_constants.ERROR: 'danger',
}

#PAGSEGURO

PAGSEGURO_TOKEN = 'FBC0605AB7D44E0091DF25007031ECAC'
PAGSEGURO_EMAIL= 'allan.turatti@gmail.com'
PAGSEGURO_SANDBOX = True
>>>>>>> master
